// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCdQeRmvebZEgB7zawftlpgLcPOa1cibY',
    appId: '1:415096554902:web:a5a642637f95077a5f09b7',
    messagingSenderId: '415096554902',
    projectId: 'eremos-puzzle',
    authDomain: 'eremos-puzzle.firebaseapp.com',
    storageBucket: 'eremos-puzzle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPSv2-y4PGR9I0ZBTBlC8e9hq9GMLlklk',
    appId: '1:415096554902:android:a395701aba70fdd45f09b7',
    messagingSenderId: '415096554902',
    projectId: 'eremos-puzzle',
    storageBucket: 'eremos-puzzle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcuddaDSUSB2n7QPrqkydPBrIzRelbhsY',
    appId: '1:415096554902:ios:16d1a2424c1799ae5f09b7',
    messagingSenderId: '415096554902',
    projectId: 'eremos-puzzle',
    storageBucket: 'eremos-puzzle.firebasestorage.app',
    iosBundleId: 'com.example.eremos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcuddaDSUSB2n7QPrqkydPBrIzRelbhsY',
    appId: '1:415096554902:ios:16d1a2424c1799ae5f09b7',
    messagingSenderId: '415096554902',
    projectId: 'eremos-puzzle',
    storageBucket: 'eremos-puzzle.firebasestorage.app',
    iosBundleId: 'com.example.eremos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCdQeRmvebZEgB7zawftlpgLcPOa1cibY',
    appId: '1:415096554902:web:269d8c01e9dc24e35f09b7',
    messagingSenderId: '415096554902',
    projectId: 'eremos-puzzle',
    authDomain: 'eremos-puzzle.firebaseapp.com',
    storageBucket: 'eremos-puzzle.firebasestorage.app',
  );

}